# Locked membership; versions are fixed by the homebrew/core revision in toolchain.lock.json.
brew "age"
brew "bat"
brew "curl"
brew "eza"
brew "fd"
brew "ffmpeg"
brew "fzf"
brew "gh"
brew "git"
brew "git-lfs"
brew "infisical"
brew "jq"
brew "just"
brew "lazygit"
brew "rclone"
brew "ripgrep"
brew "sops"
brew "stow"
brew "tree"
brew "wget"
brew "yq"
brew "zoxide"
brew "direnv"
brew "neovim"
brew "starship"
brew "tmux"
brew "tree-sitter"
brew "yazi"
brew "zellij"
brew "bun"
brew "node"
brew "python@3.13"
brew "uv"
brew "herdr"
# remote.Brewfile requests the standalone flock formula. At the locked core
# revision, util-linux is already required and conflicts on the same binary;
# make the capability provider explicit without overwriting linked files.
brew "util-linux"
brew "tailscale"
brew "ttyd"
